### ISSUE TITLE
Option to set Output Config.

### ISSUE THREAD

**Issue by mittelgrau** [johnpuddephatt/eleventy-srcset#1]
Hey, 
You created a great plugin i would love to use it myself. Only thing i was struggeling with was the configuration. As far as i can see there is no option to set the input / output folders via a config object. Could be a big enhancment. Greatly appreaciate your effort with this plugin and any reply.    
If you find the time maybe a small readme introduction would be of some help. Again thank you and stay healthy!

**Comment by johnpuddephatt** [comment]
Hey, thanks!

I've used this in a couple of personal projects and was planning on documenting it and getting it listed on the plugins page on the 11ty site at some point but I'm still working on ironing out a few things!

With the config, I followed the example of [eleventy-plugin-respimg](https://www.npmjs.com/package/eleventy-plugin-respimg) and you should be able to set config in your eleventy.js config file, e.g. 

```
eleventyConfig.srcsetAutoselector = '.page-body img';
eleventyConfig.srcsetCreateCaptions = true;
```
to override the defaults you can see in the plugin's .eleventy.js file. I'd definitely be happy to have a config object, could look a bit neater I guess.

Any other thoughts/input welcomed, might help me get this finished and publicised!

**Comment by mittelgrau** [comment]
Will definitly open a pull request in the next few days if i find the time. Wanted to get your view first 😅but good to know that it is a active project.
