### ISSUE TITLE
Can't get the automatic filter to work.

### ISSUE THREAD

**Issue by huphtur** [johnpuddephatt/eleventy-srcset#3]
Got the plugin installed and working with`{% srcset %}`, but how does one utilize the automatic filter mode?

**Comment by johnpuddephatt** [comment]
(Note this plugin is a work in progress and not recommended for use in production. I'm very happy to help but please be aware that nothing is guaranteed to work!)

The automatic mode is designed to be used for user submitted content, e.g. blog posts. It uses a specified selector to find <img> attributes within content and replaces them with responsive image markup and generates the necessary files based on the srcsetWidths array.

The default selector is `.page-body img` – this will find all `img` tags within an element with class `.page-body`.

You should be able to adjust this to whatever you like based on your site/template's markup.

**Comment by huphtur** [comment]
Ah yes, that works. I was applying `.page-body` as a class to the `img`, while in fact I had to use it as a wrapper class around image(s). 

Great stuff, would love to see where you take this plugin. Config and production options come to mind.
