### ISSUE TITLE
Can't edit default settings

### ISSUE THREAD

**Issue by fedeis** [johnpuddephatt/eleventy-srcset#5]
Hi, thanks for your very good work on this plugin.
I'm encountering some difficulties in setting custom values, overwriting the default parameters. This is the code I'm trying to use: 

```
const pluginSrcset = require('eleventy-plugin-srcset');

module.exports = function (config) {
    config.addPlugin(pluginSrcset, {
        autoselector: '.root figure',
        srcsetWidths: [320, 640, 960, 1200]
    });
``` 

The plugin works just fine with default parameters, both with autoselector and with the srcset tag.

**Comment by johnpuddephatt** [comment]
For the minute they need to be set globally, e.g.

```
eleventyConfig.autoselector = ‘.article-body img’
```

I am going to change this as it’s already been mentioned by someone else. I just went off how the eleventy cloudinary plugin sets its config options.

**Comment by johnpuddephatt** [comment]
I've just pushed some changes that address this. Config can now be set in the way you describe.
